/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useAnimations, useFBX, useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { FBXLoader } from 'three/examples/jsm/loaders/FBXLoader'

const Developer = ({ animationName = 'idle', ...props }) => {
  const group = useRef()
  const { nodes, materials } = useGLTF('/models/animations/developer.glb')

  const [idle, salute, clapping, victory] = useLoader(FBXLoader, [
    '/models/animations/idle.fbx',
    '/models/animations/salute.fbx',
    '/models/animations/clapping.fbx',
    '/models/animations/victory.fbx',
  ])
  const idleAnimation = idle.animations
  const saluteAnimation = salute.animations
  const clappingAnimation = clapping.animations
  const victoryAnimation = victory.animations

  useEffect(() => {
    idleAnimation[0].name = 'idle'
    saluteAnimation[0].name = 'salute'
    clappingAnimation[0].name = 'clapping'
    victoryAnimation[0].name = 'victory'

    const clips = [idleAnimation[0], saluteAnimation[0], clappingAnimation[0], victoryAnimation[0]];
    clips.forEach((clip) => {
      // Remove tracks that target 'Armature' (root node in FBX) as it doesn't exist in the GLTF model
      clip.tracks = clip.tracks.filter(track => !track.name.includes('Armature'));

      clip.tracks.forEach((track) => {
        // Fix Mixamo/FBX bone naming to match GLTF
        track.name = track.name.replace('mixamorig:', '');
      });

      // Final safety: Filter out any tracks that don't have a '.' (invalid property binding)
      clip.tracks = clip.tracks.filter(track => track.name.includes('.'));
    });
  }, [])

  const { actions } = useAnimations([idleAnimation[0], saluteAnimation[0], clappingAnimation[0], victoryAnimation[0]], group)

  useEffect(() => {
    const action = actions[animationName]
    if (action) {
      action.reset().fadeIn(0.5).play()
      return () => action.fadeOut(0.5)
    }
  }, [animationName, actions])

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
    </group>
  )
}

useGLTF.preload('/models/animations/developer.glb')
useFBX.preload('/models/animations/idle.fbx')
useFBX.preload('/models/animations/salute.fbx')
useFBX.preload('/models/animations/clapping.fbx')
useFBX.preload('/models/animations/victory.fbx')
export default Developer
